import re
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

GRID_POS = {
    1: (0, 0),
    2: (0, 1),
    3: (0, 2),
    4: (1, 0),
    5: (1, 1),
    6: (1, 2),
    7: (2, 0),
    8: (2, 1),
    9: (2, 2),
}


def reduce_label_set(label_set):
    """
    Simplify the label set of a given span by
       1. removing the "with_reference" label
       2. replacing distractor positions with a general "d" label
          (indicating reference to any distractor)
       3. removing the "t" prefix for target positions

    Args:
        label_set (list[str]): annotated labels for the given span

    Returns:
        tuple[str]: reduced label set for the given span
    """
    # reference set
    if "with_reference" in label_set:
        # remove reference flag
        label_set = [label for label in label_set if label != "with_reference"]
        # reduce distractor cells
        if any([label.startswith("d") for label in label_set]):
            label_set = [label for label in label_set if not label.startswith("d")]
            label_set.append("d")
        # reduce target cells and return
        label_set = [label.replace("t", "") for label in label_set]
        return tuple(sorted(label_set))

    return tuple()


def build_simple_target_heatmap(consensus, relative=False):
    """
    Aggregate targets to a 3x3 grid count.

    Args:
        consensus (list[dict]): records representing the annotation consensus for a set of items
            (e.g. created with DataFrame.to_dict(orient='records') )
        relative (bool, optional): Use relative frequencies instead of absolute counts. Defaults to False.

    Returns:
        list[list[int or float]]: Counts or frequencies for grid positions described by speakers or listeners.
    """
    grid = [[0 for _ in range(3)] for _ in range(3)]
    for item in consensus:
        for t in item.get("targets", []):
            r, c = GRID_POS[t]
            grid[r][c] += 1

    if relative:
        return (np.array(grid) / np.array(grid).sum()).tolist()

    return grid


def plot_grids(
    grid_counts,
    title="Majority lables on target",
    prec=2,
    save_path=None,
    cmap="viridis",
    vmin=0,
    vmax=0.3,
    show=True,
    draw_colorbar=True,
    ax=None
):
    """
    Render heatmaps as matplotlib figures.

    Args:
        grid_counts (list[list[int or float]]): Counts or frequencies for grid positions described by speakers or listeners
            (as generated by build_simple_target_heatmap).
        title (str, optional): Title of the figure. Defaults to "Majority lables on target".
        prec (int, optional): Precision for displaying frequencies. Defaults to 2.
        save_path (str or NoneType, optional): Path for saving the rendered figure. Figure is not saved if set to None. Defaults to None.
        cmap (str, optional): Name of the matplotlib color map. Defaults to 'viridis'.
        vmin (int, optional): Lower bound of the color bar. Defaults to 0.
        vmax (float, optional): Upper bound of the color bar. Defaults to 0.3.
    """
    
    if ax is None:
        fig, ax = plt.subplots(figsize=(4, 4))
    else:
        fig = ax.figure
    
    arr = np.array(grid_counts)
    im = ax.imshow(arr, cmap=cmap, vmin=vmin, vmax=vmax)
    for i in range(3):
        for j in range(3):
            ax.text(j, i, arr[i, j].round(prec), ha="center", va="center", fontsize=16)
    ax.set_xticks([])
    ax.set_yticks([])
    ax.set_xticklabels([])
    ax.set_yticklabels([])
    
    ax.set_title(title, fontsize=20)
    
    if draw_colorbar:
        fig.colorbar(im, ax=ax)

    if save_path is not None:
        fig.savefig(save_path, bbox_inches="tight")

    if show and ax is None:
        plt.show()

    return fig, ax


def speaker_or_listener_utt(entry):
    """
    Determine for a given span if it was produced by the speaker or listener.

    Args:
        entry (pd.Series): A single entry of the ann_df DataFrame (containing span annotations).

    Returns:
        str: A string indicating who produced the utterance ("listener" or "speaker")
    """
    full_text = entry.full_text
    start_position = entry.start
    matches = list(re.finditer(r"(speaker|listener):", full_text))
    roles = [x.group(1) for x in matches]
    utt_start_positions = [x.start() for x in matches]

    idx_array = np.array(utt_start_positions + [len(full_text)])
    utt_idx = np.where(start_position > idx_array)[0].max()
    role = roles[utt_idx]

    return role


def prepare_data(ref_ann_path, colorgrid_ann_path, ls_data_path):
    """
    Read and preprocess the data used for the analysis.

    Args:
        ref_ann_path (str): Path to the JSON file containing the span annotations.
        colorgrid_ann_path (str): Path to the JSON file containing the original color grid annotations (preprocessed as for the MLLMs-as-listeners project)
        ls_data_path (str): Path to the JSON file containing the preprocessed data used for LabelStudio

    Returns:
        tuple[pd.DataFrame, pd.DataFrame, list[str], tuple[list[str]]]:
            ann_df: pd.DataFrame containing span annotations (with further stats computed in this function)
            data_df: pd.DataFrame containing the original color grid annotations
            gameids: list containing unique identifiers for the games included in ann_df.
            far_ids, split_ids, close_ids: lists containing unique identifiers for the games included in the far, split and close partitions.

    """

    print("read ann data...")
    ann_df = (
        pd.read_json(ref_ann_path)
        .sort_values(by=["game_id", "round_num"])
        .reset_index(drop=True)
    )
    ann_df["round_id"] = ann_df.apply(lambda x: f"{x.game_id}_{x.round_num}", axis=1)
    gameids = ann_df.game_id.unique().tolist()

    # reformat combinations
    ann_df["combinations"] = ann_df.label_set.map(reduce_label_set)
    assert (
        ann_df.combinations.map(lambda x: [int(i) for i in x if i != "d"])
        == ann_df.targets
    ).all()

    print("read source data...")

    data_df = pd.read_json(colorgrid_ann_path)

    far_ids = data_df.loc[data_df.condition == "FAR"].round_id.values
    split_ids = data_df.loc[data_df.condition == "SPLIT"].round_id.values
    close_ids = data_df.loc[data_df.condition == "CLOSE"].round_id.values

    print("add further information from label studio data...")

    raw_ls_data = pd.read_json(ls_data_path)
    raw_ls_data = raw_ls_data.assign(**raw_ls_data.meta.apply(pd.Series)).drop(
        columns="meta"
    )
    raw_ls_data = raw_ls_data.assign(**raw_ls_data.data.apply(pd.Series)).drop(
        columns="data"
    )
    raw_ls_data = raw_ls_data.set_index(["game_id", "round_num"])

    ann_df["full_text"] = ann_df.apply(
        lambda x: raw_ls_data.loc[x.game_id, x.round_num].text, axis=1
    )
    ann_df["ann_url"] = ann_df.apply(
        lambda x: raw_ls_data.loc[x.game_id, x.round_num].url, axis=1
    )
    ann_df["role"] = ann_df.apply(speaker_or_listener_utt, axis=1)

    condition_map = data_df.set_index(["round_id"]).condition.to_dict()
    ann_df["condition"] = ann_df.round_id.map(condition_map)

    ann_df = ann_df.sort_values(by=["game_id", "round_num"])
    data_df = data_df.sort_values(by=["gameid", "roundNum"])

    return ann_df, data_df, gameids, (far_ids, split_ids, close_ids)
